### ISSUE TITLE
Errors with Ionic Framework

### ISSUE THREAD

**Issue by cfh463** [Tlantic/cdv-socket-plugin#65]
Sorry if this is a noob question - still getting familiar with using cordova plugins  and ionic framework. But I installed the plug in with command:

cordova plugin add com.tlantic.plugins.socket

The fetch and install went smooth and seems like it was integrated into my project, but building for iOS is getting an error:

Then when I build for iOS I get:

The following build commands failed:
    CompileC build/rr165.build/Debug-iphonesimulator/rr165.build/Objects-normal/i386/CDVSocketPlugin.o rr165/Plugins/com.tlantic.plugins.socket/CDVSocketPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/rr165.build/Debug-iphonesimulator/rr165.build/Objects-normal/i386/Connection.o rr165/Plugins/com.tlantic.plugins.socket/Connection.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Error: /Users/robgalvin/ionic/rr165/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

Any idea what this is and how to resolve? Android builds just fine. I am using the latest Xcode ad iOS SDk

**Comment by vinnylinck** [comment]
Hi there

Actually, we never tested we Ionic these days. Not sure if the issue is about Ionic itself or lack of testing regarding latest iOS SDKs. I'm about to take a look on this and see if I can figure out what's happening.

Thanks for reporting this.

**Comment by cfh463** [comment]
Actually it has nothing to do with ionic - it seems like an iOS issue. Am I missing something with compiling and getting it to work for iOS
